import { useState } from 'react'
import Button from '../components/Button'
import Card from '../components/Card'
import EmptyState from '../components/EmptyState'
import useToast from '../hooks/useToast'
import mockAdminJobs from '../data/mockAdminJobs'
import DashboardLayout from '../layouts/DashboardLayout'

const navItems = [{ label: 'Dashboard', href: '/admin/dashboard' }, { label: 'Users', href: '/admin/users' }, { label: 'Candidates', href: '/admin/candidates' }, { label: 'Companies', href: '/admin/companies' }, { label: 'Jobs', href: '/admin/jobs' }, { label: 'Projects', href: '/admin/projects' }, { label: 'Reports', href: '/admin/reports' }, { label: 'Logout', href: '/login' }]
export default function AdminJobs() {
  const { showToast } = useToast()
  const [jobs, setJobs] = useState(mockAdminJobs), [search, setSearch] = useState(''), [status, setStatus] = useState('All')
  const q = search.trim().toLowerCase(), filtered = jobs.filter((x) => (!q || x.title.toLowerCase().includes(q) || x.company.toLowerCase().includes(q)) && (status === 'All' || x.status === status))
  const remove = (job) => { if (window.confirm(`Delete “${job.title}”?`)) { setJobs((current) => current.filter((x) => x.id !== job.id)); showToast(`${job.title} was deleted.`, 'error') } }
  const Actions = ({ job }) => <div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => window.alert(`${job.title}\n${job.company}\n\n${job.description}`)}>View</Button><Button variant="danger" size="sm" onClick={() => remove(job)}>Delete</Button></div>
  return <DashboardLayout title="Jobs" navItems={navItems} userType="Admin"><AdminHeading title="Jobs" subtitle="Review and manage job posts." /><AdminFilters search={search} setSearch={setSearch} status={status} setStatus={setStatus} placeholder="Search title or company..." /><p className="mb-4 mt-8 text-sm text-[#8892b0]">Showing {filtered.length} jobs</p><Card padding="sm" className="hidden md:block"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-[#233554] text-xs text-[#64748b]"><th className="p-4">Title</th><th className="p-4">Company</th><th className="p-4">Location</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{filtered.map((job) => <tr key={job.id} className="border-b border-[#233554]/70 last:border-0"><td className="p-4 text-sm font-medium">{job.title}</td><td className="p-4 text-sm text-[#64ffda]">{job.company}</td><td className="p-4 text-xs text-[#8892b0]">{job.location}</td><td className="p-4"><Status status={job.status} /></td><td className="p-4 text-xs text-[#8892b0]">{job.createdDate}</td><td className="p-4"><Actions job={job} /></td></tr>)}</tbody></table></div></Card><div className="space-y-4 md:hidden">{filtered.map((job) => <Card key={job.id} hover><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{job.title}</h3><p className="mt-1 text-sm text-[#64ffda]">{job.company}</p></div><Status status={job.status} /></div><p className="my-4 text-xs text-[#8892b0]">{job.location} · {job.createdDate}</p><Actions job={job} /></Card>)}</div>{filtered.length === 0 && <EmptyState title="No jobs found" description="Try changing your search or status filter." />}</DashboardLayout>
}
function AdminHeading({ title, subtitle }) { return <section className="mb-8"><p className="font-mono text-sm text-[#64ffda]">Content moderation</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">{title}</h2><p className="mt-3 text-[#8892b0]">{subtitle}</p></section> }
function AdminFilters({ search, setSearch, status, setStatus, placeholder }) { return <Card><div className="grid gap-4 sm:grid-cols-[1fr_220px]"><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={placeholder} aria-label="Search" className="rounded-md border border-[#233554] bg-[#0a192f]/70 px-4 py-3 text-sm outline-none focus:border-[#64ffda]" /><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Status" className="rounded-md border border-[#233554] bg-[#0a192f]/70 px-4 py-3 text-sm outline-none focus:border-[#64ffda]">{['All', 'Open', 'Closed'].map((x) => <option key={x}>{x}</option>)}</select></div></Card> }
function Status({ status }) { return <span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${status === 'Open' ? 'bg-[#22c55e]/10 text-[#22c55e]' : 'bg-[#ef4444]/10 text-[#ef4444]'}`}>{status}</span> }
