import { useState } from 'react'
import Button from '../components/Button'
import Card from '../components/Card'
import EmptyState from '../components/EmptyState'
import useToast from '../hooks/useToast'
import mockAdminProjects from '../data/mockAdminProjects'
import DashboardLayout from '../layouts/DashboardLayout'

const navItems = [{ label: 'Dashboard', href: '/admin/dashboard' }, { label: 'Users', href: '/admin/users' }, { label: 'Candidates', href: '/admin/candidates' }, { label: 'Companies', href: '/admin/companies' }, { label: 'Jobs', href: '/admin/jobs' }, { label: 'Projects', href: '/admin/projects' }, { label: 'Reports', href: '/admin/reports' }, { label: 'Logout', href: '/login' }]
export default function AdminProjects() {
  const { showToast } = useToast()
  const [projects, setProjects] = useState(mockAdminProjects), [search, setSearch] = useState(''), [status, setStatus] = useState('All')
  const q = search.trim().toLowerCase(), filtered = projects.filter((x) => (!q || x.title.toLowerCase().includes(q) || x.company.toLowerCase().includes(q)) && (status === 'All' || x.status === status))
  const remove = (project) => { if (window.confirm(`Delete “${project.title}”?`)) { setProjects((current) => current.filter((x) => x.id !== project.id)); showToast(`${project.title} was deleted.`, 'error') } }
  const Actions = ({ project }) => <div className="flex justify-end gap-2"><Button variant="outline" size="sm" onClick={() => window.alert(`${project.title}\n${project.company}\n${project.budget}\n\n${project.description}`)}>View</Button><Button variant="danger" size="sm" onClick={() => remove(project)}>Delete</Button></div>
  return <DashboardLayout title="Projects" navItems={navItems} userType="Admin"><section className="mb-8"><p className="font-mono text-sm text-[#64ffda]">Content moderation</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">Projects</h2><p className="mt-3 text-[#8892b0]">Review and manage company projects.</p></section><Card><div className="grid gap-4 sm:grid-cols-[1fr_220px]"><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search title or company..." aria-label="Search projects" className="rounded-md border border-[#233554] bg-[#0a192f]/70 px-4 py-3 text-sm outline-none focus:border-[#64ffda]" /><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Status" className="rounded-md border border-[#233554] bg-[#0a192f]/70 px-4 py-3 text-sm outline-none focus:border-[#64ffda]">{['All', 'Open', 'Closed'].map((x) => <option key={x}>{x}</option>)}</select></div></Card><p className="mb-4 mt-8 text-sm text-[#8892b0]">Showing {filtered.length} projects</p><Card padding="sm" className="hidden md:block"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead><tr className="border-b border-[#233554] text-xs text-[#64748b]"><th className="p-4">Title</th><th className="p-4">Company</th><th className="p-4">Budget</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{filtered.map((project) => <tr key={project.id} className="border-b border-[#233554]/70 last:border-0"><td className="p-4 text-sm font-medium">{project.title}</td><td className="p-4 text-sm text-[#64ffda]">{project.company}</td><td className="p-4 text-sm">{project.budget}</td><td className="p-4"><span className={project.status === 'Open' ? 'text-[#22c55e]' : 'text-[#ef4444]'}>{project.status}</span></td><td className="p-4 text-xs text-[#8892b0]">{project.createdDate}</td><td className="p-4"><Actions project={project} /></td></tr>)}</tbody></table></div></Card><div className="space-y-4 md:hidden">{filtered.map((project) => <Card key={project.id} hover><div className="flex justify-between gap-3"><div><h3 className="font-semibold">{project.title}</h3><p className="mt-1 text-sm text-[#64ffda]">{project.company}</p></div><span className={project.status === 'Open' ? 'text-[#22c55e]' : 'text-[#ef4444]'}>{project.status}</span></div><p className="my-4 text-sm">{project.budget}</p><p className="mb-4 text-xs text-[#8892b0]">Created {project.createdDate}</p><Actions project={project} /></Card>)}</div>{filtered.length === 0 && <EmptyState title="No projects found" description="Try changing your search or status filter." />}</DashboardLayout>
}
