import { useState } from 'react'
import Button from '../components/Button'
import Card from '../components/Card'
import mockAdminUsers from '../data/mockAdminUsers'
import DashboardLayout from '../layouts/DashboardLayout'

const navItems = [{ label: 'Dashboard', href: '/admin/dashboard' }, { label: 'Users', href: '/admin/users' }, { label: 'Candidates', href: '/admin/candidates' }, { label: 'Companies', href: '/admin/companies' }, { label: 'Jobs', href: '/admin/jobs' }, { label: 'Projects', href: '/admin/projects' }, { label: 'Reports', href: '/admin/reports' }, { label: 'Logout', href: '/login' }]
const control = 'w-full rounded-md border border-[#233554] bg-[#0a192f]/70 px-4 py-3 text-sm text-[#e6f1ff] outline-none placeholder:text-[#64748b] focus:border-[#64ffda]'
const roleStyle = { Admin: 'bg-[#64ffda]/10 text-[#64ffda]', Candidate: 'bg-blue-500/10 text-blue-300', Company: 'bg-violet-500/10 text-violet-300' }

export default function AdminUsers() {
  const [users, setUsers] = useState(mockAdminUsers), [search, setSearch] = useState(''), [role, setRole] = useState('All'), [status, setStatus] = useState('All')
  const query = search.trim().toLowerCase()
  const filtered = users.filter((item) => (!query || item.name.toLowerCase().includes(query) || item.email.toLowerCase().includes(query)) && (role === 'All' || item.role === role) && (status === 'All' || item.status === status))
  const toggle = (id) => setUsers((current) => current.map((item) => item.id === id ? { ...item, status: item.status === 'Active' ? 'Disabled' : 'Active' } : item))
  const remove = (item) => { if (window.confirm(`Delete ${item.name}?`)) setUsers((current) => current.filter((user) => user.id !== item.id)) }
  const Actions = ({ user }) => <div className="flex flex-wrap justify-end gap-2"><Button variant="ghost" size="sm" onClick={() => window.alert(`${user.name}\n${user.email}\n${user.role} · ${user.status}`)}>View</Button><Button variant="outline" size="sm" onClick={() => toggle(user.id)}>{user.status === 'Active' ? 'Disable' : 'Enable'}</Button><Button variant="danger" size="sm" onClick={() => remove(user)}>Delete</Button></div>
  const Badge = ({ user }) => <><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${roleStyle[user.role]}`}>{user.role}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${user.status === 'Active' ? 'bg-[#22c55e]/10 text-[#22c55e]' : 'bg-[#ef4444]/10 text-[#ef4444]'}`}>{user.status}</span></>
  return <DashboardLayout title="Users" navItems={navItems} userType="Admin"><div className="space-y-8"><section><p className="font-mono text-sm text-[#64ffda]">User management</p><h2 className="mt-2 text-2xl font-bold sm:text-3xl">Users</h2><p className="mt-3 text-[#8892b0]">Manage all platform users.</p></section><Card><div className="grid gap-4 md:grid-cols-3"><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or email..." aria-label="Search users" className={control} /><select value={role} onChange={(e) => setRole(e.target.value)} aria-label="Filter role" className={control}>{['All', 'Candidate', 'Company', 'Admin'].map((x) => <option key={x}>{x}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} aria-label="Filter status" className={control}>{['All', 'Active', 'Disabled'].map((x) => <option key={x}>{x}</option>)}</select></div></Card><section><p className="mb-4 text-sm text-[#8892b0]">Showing {filtered.length} users</p><Card padding="sm" className="hidden md:block"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-[#233554] text-xs text-[#64748b]"><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.id} className="border-b border-[#233554]/70 last:border-0"><td className="p-4 text-sm font-medium">{user.name}</td><td className="p-4 text-sm text-[#8892b0]">{user.email}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-[10px] ${roleStyle[user.role]}`}>{user.role}</span></td><td className="p-4"><span className={user.status === 'Active' ? 'text-[#22c55e]' : 'text-[#ef4444]'}>{user.status}</span></td><td className="p-4 text-xs text-[#8892b0]">{user.createdDate}</td><td className="p-4"><Actions user={user} /></td></tr>)}</tbody></table></div></Card><div className="space-y-4 md:hidden">{filtered.map((user) => <Card key={user.id} hover><h3 className="font-semibold">{user.name}</h3><p className="mt-1 text-sm text-[#8892b0]">{user.email}</p><div className="mt-4 flex gap-2"><Badge user={user} /></div><p className="my-4 text-xs text-[#64748b]">Created {user.createdDate}</p><Actions user={user} /></Card>)}</div></section></div></DashboardLayout>
}
