const skillOptions = [
  'JavaScript', 'TypeScript', 'Python', 'Java', 'C#', 'C++', 'C', 'PHP', 'Go',
  'Rust', 'Ruby', 'Kotlin', 'Swift', 'Dart', 'Scala', 'R', 'MATLAB', 'SQL',
  'Bash', 'PowerShell', 'Lua', 'Elixir', 'Haskell', 'Solidity', 'HTML', 'CSS',
  'Sass', 'Tailwind CSS', 'Bootstrap', 'React', 'Next.js', 'Vue.js', 'Nuxt.js',
  'Angular', 'Svelte', 'SvelteKit', 'Redux', 'Zustand', 'Material UI',
  'shadcn/ui', 'Vite', 'Webpack', 'React Native', 'Flutter',
  'Android Development', 'iOS Development', 'Node.js', 'Express.js', 'NestJS',
  'Laravel', 'Symfony', 'Django', 'Flask', 'FastAPI', 'Spring Boot',
  'ASP.NET Core', 'Ruby on Rails', 'Gin', 'REST APIs', 'GraphQL', 'WebSockets',
  'Microservices', 'API Design', 'MySQL', 'PostgreSQL', 'SQLite',
  'Microsoft SQL Server', 'MongoDB', 'Redis', 'Firebase', 'Supabase',
  'Oracle Database', 'MariaDB', 'Elasticsearch', 'Prisma', 'Eloquent ORM',
  'Data Modeling', 'Database Design', 'Git', 'GitHub', 'GitLab', 'Docker',
  'Kubernetes', 'Linux', 'Nginx', 'Apache', 'AWS', 'Microsoft Azure',
  'Google Cloud', 'Cloudflare', 'Vercel', 'Netlify', 'CI/CD', 'GitHub Actions',
  'Terraform', 'Ansible', 'Jenkins', 'DevOps', 'PHPUnit', 'Pest', 'Jest',
  'Vitest', 'Cypress', 'Playwright', 'Selenium', 'Postman', 'Unit Testing',
  'Integration Testing', 'Test Automation', 'Debugging', 'Code Review',
  'Clean Code', 'Design Patterns', 'Machine Learning', 'Artificial Intelligence',
  'Data Science', 'Data Analysis', 'Pandas', 'NumPy', 'TensorFlow', 'PyTorch',
  'OpenAI API', 'Cybersecurity', 'Web Security', 'OAuth', 'Laravel Sanctum',
  'JWT', 'Figma', 'UI Design', 'UX Design', 'Responsive Design',
  'Accessibility', 'Product Management', 'Project Management', 'Agile',
  'Scrum', 'Jira', 'Technical Writing', 'Problem Solving', 'Teamwork',
  'Communication',
]

export default [...new Set(skillOptions)].sort((a, b) => a.localeCompare(b))
